// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXmU6lbRmXxSsOZBFXZgG_8MdoBkYI2XM',
    appId: '1:390129434319:web:5f597bcf44a852dd3681ba',
    messagingSenderId: '390129434319',
    projectId: 'applist-81ad8',
    authDomain: 'applist-81ad8.firebaseapp.com',
    storageBucket: 'applist-81ad8.appspot.com',
    measurementId: 'G-FJ13ZM9V6P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6LaRYQTD_GT0MHMMG3NXSGJ02sJxpPZU',
    appId: '1:390129434319:android:4a92a3da669649513681ba',
    messagingSenderId: '390129434319',
    projectId: 'applist-81ad8',
    storageBucket: 'applist-81ad8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtrygCmdH0mzB0vXzA7_7MZRHRoge3dII',
    appId: '1:390129434319:ios:f8bdfdfb34f14ff43681ba',
    messagingSenderId: '390129434319',
    projectId: 'applist-81ad8',
    storageBucket: 'applist-81ad8.appspot.com',
    iosBundleId: 'com.example.apptodolist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtrygCmdH0mzB0vXzA7_7MZRHRoge3dII',
    appId: '1:390129434319:ios:f8bdfdfb34f14ff43681ba',
    messagingSenderId: '390129434319',
    projectId: 'applist-81ad8',
    storageBucket: 'applist-81ad8.appspot.com',
    iosBundleId: 'com.example.apptodolist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXmU6lbRmXxSsOZBFXZgG_8MdoBkYI2XM',
    appId: '1:390129434319:web:167032f404f488f23681ba',
    messagingSenderId: '390129434319',
    projectId: 'applist-81ad8',
    authDomain: 'applist-81ad8.firebaseapp.com',
    storageBucket: 'applist-81ad8.appspot.com',
    measurementId: 'G-WKH117PL12',
  );
}
